from __future__ import annotations

# Shared static CSS/JS blocks for digest HTML rendering.

DIGEST_PAGE_STYLE = (
    "    :root { color-scheme: light; --bg:#f3f6fb; --panel:#ffffff; --ink:#0f172a; --muted:#475569; --line:#dbe3ef; --line-2:#c9d5e6; --brand:#2563eb; --brand-2:#1d4ed8; --radius:14px; --shadow:0 10px 30px rgba(2, 6, 23, .06), 0 2px 8px rgba(2, 6, 23, .05); }\n"
    "    body { font-family: Inter, Segoe UI, Arial, sans-serif; margin: 0; background: radial-gradient(1200px 550px at 15% -15%, #e0ebff 0%, transparent 60%), radial-gradient(1000px 420px at 100% -30%, #e8f0ff 0%, transparent 58%), var(--bg); color: var(--ink); }\n"
    "    * { box-sizing: border-box; }\n"
    "    .page { max-width: 1120px; margin: 26px auto 40px; padding: 0 22px 36px; }\n"
    "    .header { margin: 0 0 16px; padding: 20px 22px; border: 1px solid var(--line); border-radius: var(--radius); background: linear-gradient(160deg, #ffffff 0%, #f9fbff 100%); box-shadow: var(--shadow); }\n"
    "    .title { font-size: clamp(28px, 4vw, 40px); font-weight: 800; margin: 0 0 10px; letter-spacing: -0.03em; line-height: 1.08; color: #0b1732; }\n"
    "    .meta { color: var(--muted); font-size: 13px; margin: 3px 0; font-weight: 500; }\n"
    "    .card { background: var(--panel); border: 1px solid var(--line); border-radius: var(--radius); padding: 20px 22px 16px; margin: 14px 0; box-shadow: var(--shadow); transition: transform .16s ease, box-shadow .16s ease, border-color .16s ease; }\n"
    "    .card:hover { transform: translateY(-1px); border-color: var(--line-2); box-shadow: 0 14px 30px rgba(2,6,23,.08), 0 2px 9px rgba(2,6,23,.06); }\n"
    "    .card h2 { margin: 0 0 10px; font-size: 25px; line-height: 1.24; letter-spacing: -.015em; color: #0f172a; }\n"
    "    .card-meta { color: #64748b; font-size: 12px; margin-bottom: 11px; font-weight: 600; }\n"
    "    .summary { font-size: 15px; line-height: 1.72; margin: 0; color: #111827; }\n"
    "    .controls { background: var(--panel); border: 1px solid var(--line); border-radius: var(--radius); padding: 16px 18px; margin: 0 0 16px; box-shadow: var(--shadow); }\n"
    "    .visually-hidden { position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap;border:0; }\n"
    "    .controls-toolbar { display:grid; grid-template-columns: minmax(0,1fr) auto; gap:10px 14px; align-items:start; margin-bottom:0; }\n"
    "    .controls-search-form { display:flex; gap:8px; align-items:stretch; width:100%; min-width:0; }\n"
    "    .controls-search-form input[type=search] { flex:1; min-width:0; width:auto; }\n"
    "    .controls-search-form button[type=submit] { flex-shrink:0; white-space:nowrap; }\n"
    "    .controls-toolbar-meta { display:flex; align-items:center; gap:10px; flex-wrap:wrap; justify-self:end; }\n"
    "    .search-hint { font-size:11px; color:#92400e; margin:0; max-width:42ch; }\n"
    "    .controls-filters-details { border:1px solid var(--line); border-radius:12px; background:#f8fbff; margin-top:12px; overflow:hidden; }\n"
    "    .controls-filters-summary { list-style:none; cursor:pointer; font-size:13px; font-weight:600; color:#374151; padding:12px 14px; display:flex; align-items:center; justify-content:space-between; gap:12px; user-select:none; }\n"
    "    .controls-filters-summary::-webkit-details-marker { display:none; }\n"
    "    .controls-filters-summary .summary-chev { color:#6b7280; font-size:11px; transition:transform .15s; }\n"
    "    .controls-filters-details[open] .summary-chev { transform:rotate(180deg); }\n"
    "    .controls-filters-inner { padding:2px 14px 16px; border-top:1px solid #e8eaed; background:#fff; }\n"
    "    .controls-section-title { font-size: 11px; font-weight: 700; color: #6b7280; text-transform: uppercase; letter-spacing: .08em; margin: 0 0 10px; }\n"
    "    .controls-subtitle { font-size: 11px; font-weight: 600; color: #9ca3af; text-transform: uppercase; letter-spacing: .06em; margin: 14px 0 8px; }\n"
    "    .controls-grid { display: grid; grid-template-columns: minmax(0,1fr); gap: 16px; align-items: start; }\n"
    "    .controls-grid--with-sources { grid-template-columns: minmax(0,1fr) minmax(240px,300px); align-items: stretch; }\n"
    "    .controls-main { min-width: 0; }\n"
    "    .controls-grid--with-sources .controls-main { display: flex; flex-direction: column; min-height: 0; }\n"
    "    .controls-grid--with-sources .controls-panel { flex: 1; }\n"
    "    .controls-panel { background: linear-gradient(180deg, #f7faff 0%, #fff 52%); border: 1px solid var(--line); border-radius: 12px; padding: 16px 18px 18px; }\n"
    "    .controls-block-sep { height: 1px; background: linear-gradient(90deg, transparent, #e5e7eb 12%, #e5e7eb 88%, transparent); margin: 18px 0; border: 0; }\n"
    "    .controls-column--right { display: flex; flex-direction: column; gap: 0; min-width: 0; align-self: stretch; }\n"
    "    .controls-grid--with-sources .controls-column--right { flex: 1; min-height: 0; }\n"
    "    .controls-group { min-width: 0; }\n"
    "    .controls-fields { display: grid; gap: 10px 12px; align-items: end; }\n"
    "    .controls-fields--dates { grid-template-columns: repeat(2, minmax(0,1fr)); max-width: 420px; }\n"
    "    .controls-fields--scores { grid-template-columns: repeat(auto-fill, minmax(118px, 1fr)); }\n"
    "    .controls-fields--sort { grid-template-columns: repeat(2, minmax(0,1fr)); max-width: 440px; gap: 12px 16px; }\n"
    "    .controls label { font-size: 12px; font-weight: 500; color: #4b5563; display: block; margin-bottom: 5px; line-height: 1.3; }\n"
    "    .controls input, .controls select { width: 100%; border: 1px solid #cbd5e1; border-radius: 10px; padding: 9px 11px; font-size: 13px; color: #0f172a; background: #fff; transition: border-color .15s, box-shadow .15s; }\n"
    "    .controls input:hover, .controls select:hover { border-color: #9ca3af; }\n"
    "    .controls input:focus, .controls select:focus { outline: none; border-color: #2563eb; box-shadow: 0 0 0 3px rgba(37,99,235,.12); }\n"
    "    .controls-actions { display: flex; justify-content: space-between; align-items: center; margin-top: 14px; padding-top: 2px; }\n"
    "    .controls button { border: 1px solid #c9d5e6; background: linear-gradient(180deg, #fff 0%, #f8fbff 100%); border-radius: 10px; padding: 8px 14px; font-size: 13px; font-weight: 600; color: #1e293b; cursor: pointer; box-shadow: 0 1px 0 rgba(15,23,42,.06); }\n"
    "    .controls button:hover { background: #eef5ff; border-color: #94a3b8; }\n"
    "    .result-count { font-size: 13px; color: #6b7280; font-variant-numeric: tabular-nums; }\n"
    "    @media (max-width: 900px) {\n"
    "      .controls-grid--with-sources { grid-template-columns: 1fr; }\n"
    "      .controls-grid--with-sources .sources-details[open] { flex: none; }\n"
    "      .controls-grid--with-sources .source-list-wrap { flex: none; max-height: min(38vh, 260px); }\n"
    "    }\n"
    "    @media (max-width: 520px) { .controls-fields--dates, .controls-fields--sort { grid-template-columns: 1fr; max-width: none; } }\n"
    "    .sources-facet { align-self: stretch; width: 100%; }\n"
    "    .controls-grid--with-sources .sources-facet { flex: 1; display: flex; flex-direction: column; min-height: 0; }\n"
    "    .sources-details { border: 1px solid #e5e7eb; border-radius: 10px; padding: 10px 10px 8px; background: #fafbfc; }\n"
    "    .controls-grid--with-sources .sources-details[open] { flex: 1; display: flex; flex-direction: column; min-height: 0; }\n"
    "    .sources-summary { list-style: none; cursor: pointer; display: flex; align-items: center; justify-content: space-between; font-size: 13px; font-weight: 700; color: #111827; padding: 2px 0 8px; }\n"
    "    .sources-summary::-webkit-details-marker { display: none; }\n"
    "    .sources-chevron { display: inline-block; width: 1em; text-align: center; color: #6b7280; transition: transform .15s; }\n"
    "    details[open] .sources-chevron { transform: rotate(0deg); }\n"
    "    details:not([open]) .sources-chevron { transform: rotate(-90deg); }\n"
    "    .sources-hint { font-size: 11px; color: #6b7280; margin: 0 0 8px; line-height: 1.35; }\n"
    "    .source-list-wrap { max-height: min(38vh, 260px); overflow-y: auto; border: 1px solid var(--line); border-radius: 10px; background: #fff; padding: 4px 6px; }\n"
    "    .controls-grid--with-sources .sources-hint { flex-shrink: 0; }\n"
    "    .controls-grid--with-sources .source-list-wrap { flex: 1 1 0; min-height: 0; max-height: none; overflow-y: auto; }\n"
    "    .controls-grid--with-sources .source-show-more { flex-shrink: 0; }\n"
    "    .source-row--select-all { display: flex; align-items: center; padding: 6px 4px 8px; margin: 0 0 4px; border-bottom: 1px solid #e5e7eb; font-size: 13px; font-weight: 600; color: #374151; }\n"
    "    .source-row--select-all label { display: flex; align-items: center; gap: 8px; cursor: pointer; margin: 0; width: 100%; }\n"
    "    .source-row--select-all input[type=checkbox] { width: 16px; height: 16px; flex-shrink: 0; margin: 0; accent-color: #2563eb; }\n"
    "    .source-list { list-style: none; margin: 0; padding: 0; }\n"
    "    .source-row { display: flex; align-items: center; gap: 8px; padding: 4px 0; font-size: 13px; color: #374151; }\n"
    "    .source-row label { display: flex; align-items: center; gap: 8px; flex: 1; min-width: 0; cursor: pointer; margin: 0; font-size: 13px; }\n"
    "    .source-row input[type=checkbox] { width: 16px; height: 16px; flex-shrink: 0; margin: 0; accent-color: #2563eb; }\n"
    "    .source-favicon { width: 20px; height: 20px; flex-shrink: 0; border-radius: 4px; object-fit: contain; background: #fff; border: 1px solid #e5e7eb; }\n"
    "    .source-label-text { flex: 1; min-width: 0; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }\n"
    "    .source-count { color: #6b7280; flex-shrink: 0; font-variant-numeric: tabular-nums; }\n"
    "    .source-count.source-count--zero { color: #9ca3af; }\n"
    "    .source-row--extra { display: none !important; }\n"
    "    .source-row.source-row--hidden { display: none !important; }\n"
    "    .source-show-more { display: block; width: 100%; margin-top: 6px; padding: 4px 0; border: none; background: none; color: #2563eb; font-size: 13px; cursor: pointer; text-align: left; }\n"
    "    .source-show-more:hover { text-decoration: underline; }\n"
    "    .refs { margin-top: 14px; padding-top: 10px; border-top: 1px solid #e5e7eb; }\n"
    "    .refs-title { font-size: 13px; font-weight: 600; color: #4b5563; margin: 0 0 6px; text-transform: uppercase; letter-spacing: .05em; }\n"
    "    .refs ul { margin: 0; padding-left: 18px; }\n"
    "    .refs li { margin: 6px 0; word-break: break-all; }\n"
    "    a { color: var(--brand-2); text-decoration: none; font-weight: 500; }\n"
    "    a:hover { text-decoration: underline; }\n"
    "    #search_btn { background: linear-gradient(180deg, #2563eb 0%, #1d4ed8 100%); color:#fff; border-color:#1e40af; }\n"
    "    #search_btn:hover { background: linear-gradient(180deg, #1d4ed8 0%, #1e40af 100%); color:#fff; }\n"
    "    #reset_filters { color:#334155; }\n"
)

DIGEST_PAGE_SCRIPT = (
    "    (function(){\n"
    "      const container = document.getElementById('cards_container');\n"
    "      const cards = Array.from(container.querySelectorAll('.card'));\n"
    "      const el = (id) => document.getElementById(id);\n"
    "      let searchIndex = { texts: [], embeddings: [], dim: 0 };\n"
    "      const idxNode = document.getElementById('digest-search-index');\n"
    "      if (idxNode) { try { searchIndex = JSON.parse(idxNode.textContent); } catch (e) {} }\n"
    "      let queryEmb = null;\n"
    "      let committedQuery = '';\n"
    "      let embeddingSeq = 0;\n"
    "      let searchScores = cards.map(function() { return 1; });\n"
    "      const inputs = {\n"
    "        dateFrom: el('date_from'), dateTo: el('date_to'),\n"
    "        minRel: el('min_relevance'), minImp: el('min_importance'), minNov: el('min_novelty'),\n"
    "        minTrust: el('min_trust'), minComp: el('min_composed'),\n"
    "        sortBy: el('sort_by'), sortOrder: el('sort_order'),\n"
    "        searchQ: el('search_q'), searchForm: el('search_form'), searchBtn: el('search_btn'),\n"
    "        reset: el('reset_filters'), count: el('result_count')\n"
    "      };\n"
    "      let searchBusy = false;\n"
    "      function num(v){ const n=parseFloat(v); return Number.isFinite(n)?n:0; }\n"
    "      function parseDate(v){ return v ? new Date(v + 'T00:00:00Z').getTime() : null; }\n"
    "      function searchTerms(query) {\n"
    "        const q = (query || '').trim().toLowerCase();\n"
    "        if (!q) return [];\n"
    "        return q.split(/\\s+/).map(function(w) {\n"
    "          return w.replace(/^['\".,;:!?()[\\]{}]+|['\".,;:!?()[\\]{}]+$/g, '');\n"
    "        }).filter(function(w) { return w.length > 0; });\n"
    "      }\n"
    "      function wordTokens(textLower) {\n"
    "        return (textLower.match(/[a-z0-9]+/gi) || []);\n"
    "      }\n"
    "      function termMatchesSearchable(term, textLower) {\n"
    "        if (!term || !textLower) return false;\n"
    "        var t = term.toLowerCase();\n"
    "        var hay = textLower.toLowerCase();\n"
    "        var words = wordTokens(hay);\n"
    "        var i;\n"
    "        for (i = 0; i < words.length; i++) {\n"
    "          var w = words[i].toLowerCase();\n"
    "          if (w === t) return true;\n"
    "          if (t.length >= 3 && w.length >= t.length && w.indexOf(t) === 0) return true;\n"
    "        }\n"
    "        return false;\n"
    "      }\n"
    "      function keywordScore(query, text) {\n"
    "        const t = (text || '').toLowerCase();\n"
    "        const terms = searchTerms(query);\n"
    "        if (!terms.length) return 1;\n"
    "        let hit = 0;\n"
    "        terms.forEach(function(w) { if (termMatchesSearchable(w, t)) hit++; });\n"
    "        return hit / terms.length;\n"
    "      }\n"
    "      function dot(a, b) {\n"
    "        let s = 0;\n"
    "        const n = Math.min(a.length, b.length);\n"
    "        for (let i = 0; i < n; i++) s += a[i] * b[i];\n"
    "        return s;\n"
    "      }\n"
    "      function computeSearchScores() {\n"
    "        const q = committedQuery;\n"
    "        const titles = searchIndex.titles || [];\n"
    "        const summaries = searchIndex.summaries || [];\n"
    "        const embs = searchIndex.embeddings || [];\n"
    "        if (!q) {\n"
    "          searchScores = cards.map(function() { return 1; });\n"
    "          return;\n"
    "        }\n"
    "        searchScores = cards.map(function(card, i) {\n"
    "          const titleT = (titles[i] != null && titles[i] !== '') ? titles[i] : ((card && card.dataset && card.dataset.title) ? card.dataset.title : '');\n"
    "          const summaryT = summaries[i] != null ? summaries[i] : '';\n"
    "          const kw = Math.max(keywordScore(q, titleT), keywordScore(q, summaryT));\n"
    "          let sem = 0;\n"
    "          const hasSem = queryEmb && embs[i] && embs[i].length === queryEmb.length;\n"
    "          if (hasSem) {\n"
    "            sem = Math.max(0, Math.min(1, dot(queryEmb, embs[i])));\n"
    "          }\n"
    "          if (hasSem) return 0.5 * kw + 0.5 * sem;\n"
    "          return kw;\n"
    "        });\n"
    "      }\n"
    "      function l2norm(v) {\n"
    "        let s = 0;\n"
    "        for (let i = 0; i < v.length; i++) s += v[i] * v[i];\n"
    "        return Math.sqrt(s);\n"
    "      }\n"
    "      function normalizeVec(v) {\n"
    "        const n = l2norm(v);\n"
    "        if (!n) return v;\n"
    "        return v.map(function(x) { return x / n; });\n"
    "      }\n"
    "      function buildLocalQueryEmbedding(q) {\n"
    "        const embs = searchIndex.embeddings || [];\n"
    "        if (!q || !embs.length) return null;\n"
    "        let dim = Number.isFinite(searchIndex.dim) ? searchIndex.dim : 0;\n"
    "        if (!dim && embs[0] && embs[0].length) dim = embs[0].length;\n"
    "        if (!dim) return null;\n"
    "        const titles = searchIndex.titles || [];\n"
    "        const summaries = searchIndex.summaries || [];\n"
    "        const acc = Array.from({ length: dim }, function() { return 0; });\n"
    "        let wSum = 0;\n"
    "        for (let i = 0; i < embs.length; i++) {\n"
    "          const e = embs[i];\n"
    "          if (!e || e.length !== dim) continue;\n"
    "          const titleT = titles[i] != null ? titles[i] : '';\n"
    "          const summaryT = summaries[i] != null ? summaries[i] : '';\n"
    "          const w = Math.max(keywordScore(q, titleT), keywordScore(q, summaryT));\n"
    "          if (w <= 0) continue;\n"
    "          for (let d = 0; d < dim; d++) acc[d] += e[d] * w;\n"
    "          wSum += w;\n"
    "        }\n"
    "        if (wSum <= 0) return null;\n"
    "        for (let d = 0; d < dim; d++) acc[d] = acc[d] / wSum;\n"
    "        return normalizeVec(acc);\n"
    "      }\n"
    "      function searchEmbeddingIndexBroken() {\n"
    "        if (!cards.length) return false;\n"
    "        const embs = searchIndex.embeddings || [];\n"
    "        const dim = Number.isFinite(searchIndex.dim) ? searchIndex.dim : 0;\n"
    "        if (dim <= 0) return true;\n"
    "        for (let i = 0; i < embs.length; i++) {\n"
    "          const e = embs[i];\n"
    "          if (e && e.length === dim) return false;\n"
    "        }\n"
    "        return true;\n"
    "      }\n"
    "      async function refreshQueryEmbedding(q) {\n"
    "        const hint = document.getElementById('search_semantic_hint');\n"
    "        queryEmb = buildLocalQueryEmbedding(q);\n"
    "        if (!hint) return;\n"
    "        if (!q) {\n"
    "          hint.hidden = true;\n"
    "          return;\n"
    "        }\n"
    "        if (searchEmbeddingIndexBroken()) {\n"
    "          hint.textContent = 'Search index incomplete; keyword matching only.';\n"
    "          hint.hidden = false;\n"
    "          return;\n"
    "        }\n"
    "        hint.hidden = true;\n"
    "      }\n"
    "      async function applySemanticEmbeddingWhenReady(q, seq) {\n"
    "        await refreshQueryEmbedding(q);\n"
    "        if (seq !== embeddingSeq || q !== committedQuery) return;\n"
    "        computeSearchScores();\n"
    "        apply();\n"
    "      }\n"
    "      async function runSearch() {\n"
    "        if (searchBusy) return;\n"
    "        searchBusy = true;\n"
    "        if (inputs.searchBtn) { inputs.searchBtn.disabled = true; inputs.searchBtn.textContent = 'Searching…'; }\n"
    "        try {\n"
    "          committedQuery = inputs.searchQ ? inputs.searchQ.value.trim() : '';\n"
    "          queryEmb = null;\n"
    "          const seq = ++embeddingSeq;\n"
    "          computeSearchScores();\n"
    "          apply();\n"
    "          void applySemanticEmbeddingWhenReady(committedQuery, seq);\n"
    "        } finally {\n"
    "          searchBusy = false;\n"
    "          if (inputs.searchBtn) { inputs.searchBtn.disabled = false; inputs.searchBtn.textContent = 'Search'; }\n"
    "        }\n"
    "      }\n"
    "      function visibleSourceFilters() {\n"
    "        return Array.from(document.querySelectorAll('.source-filter')).filter(function(b) {\n"
    "          const row = b.closest('li.source-row');\n"
    "          return row && !row.classList.contains('source-row--hidden');\n"
    "        });\n"
    "      }\n"
    "      function sourceMatches(card){\n"
    "        const raw = card.dataset.sources || '';\n"
    "        const parts = raw.split(/\\s+/).filter(Boolean);\n"
    "        if (!parts.length) return true;\n"
    "        const boxes = visibleSourceFilters();\n"
    "        if (!boxes.length) return true;\n"
    "        const checked = boxes.filter(function(b){ return b.checked; }).map(function(b){ return b.value; });\n"
    "        if (checked.length === 0) return true;\n"
    "        return parts.some(function(p){ return checked.indexOf(p) !== -1; });\n"
    "      }\n"
    "      function queryTermsHitTitleOrSummary(query, idx, card) {\n"
    "        const titles = searchIndex.titles || [];\n"
    "        const summaries = searchIndex.summaries || [];\n"
    "        const titleT = (titles[idx] != null && titles[idx] !== '') ? titles[idx] : ((card && card.dataset && card.dataset.title) ? card.dataset.title : '');\n"
    "        const summaryT = summaries[idx] != null ? summaries[idx] : '';\n"
    "        const tl = (titleT || '').toLowerCase();\n"
    "        const sl = (summaryT || '').toLowerCase();\n"
    "        const terms = searchTerms(query);\n"
    "        if (!terms.length) return true;\n"
    "        return terms.every(function(term) {\n"
    "          return termMatchesSearchable(term, tl) || termMatchesSearchable(term, sl);\n"
    "        });\n"
    "      }\n"
    "      function searchMatches(card) {\n"
    "        if (!committedQuery) return true;\n"
    "        const idx = parseInt(card.dataset.cardIdx, 10);\n"
    "        if (!Number.isFinite(idx) || searchScores[idx] === undefined) return false;\n"
    "        if (!queryTermsHitTitleOrSummary(committedQuery, idx, card)) return false;\n"
    "        return true;\n"
    "      }\n"
    "      function cardPassesDateAndScores(card) {\n"
    "        const minRel=num(inputs.minRel.value), minImp=num(inputs.minImp.value), minNov=num(inputs.minNov.value), minTrust=num(inputs.minTrust.value), minComp=num(inputs.minComp.value);\n"
    "        const from=parseDate(inputs.dateFrom.value), to=parseDate(inputs.dateTo.value);\n"
    "        const rel=num(card.dataset.relevance), imp=num(card.dataset.importance), nov=num(card.dataset.novelty), trust=num(card.dataset.trust), comp=num(card.dataset.composed);\n"
    "        const t=parseDate(card.dataset.date || '');\n"
    "        const dateOk = (!from || (t && t >= from)) && (!to || (t && t <= to));\n"
    "        return dateOk && rel >= minRel && imp >= minImp && nov >= minNov && trust >= minTrust && comp >= minComp;\n"
    "      }\n"
    "      function cardInFilterPool(card) {\n"
    "        return cardPassesDateAndScores(card) && searchMatches(card);\n"
    "      }\n"
    "      function updateSourceFacetCounts() {\n"
    "        const boxes = Array.from(document.querySelectorAll('.source-filter'));\n"
    "        if (!boxes.length) return;\n"
    "        const tallies = {};\n"
    "        boxes.forEach(function(b) { tallies[b.value] = 0; });\n"
    "        cards.forEach(function(card) {\n"
    "          if (!cardInFilterPool(card)) return;\n"
    "          const parts = (card.dataset.sources || '').split(/\\s+/).filter(Boolean);\n"
    "          parts.forEach(function(p) {\n"
    "            if (Object.prototype.hasOwnProperty.call(tallies, p)) tallies[p]++;\n"
    "          });\n"
    "        });\n"
    "        boxes.forEach(function(b) {\n"
    "          const n = tallies[b.value] || 0;\n"
    "          const lab = b.closest('label');\n"
    "          const span = lab && lab.querySelector('.source-count');\n"
    "          const row = b.closest('li.source-row');\n"
    "          if (row) {\n"
    "            const wasHidden = row.classList.contains('source-row--hidden');\n"
    "            row.classList.toggle('source-row--hidden', n === 0);\n"
    "            if (n === 0) b.checked = false;\n"
    "            else if (wasHidden) b.checked = true;\n"
    "          }\n"
    "          if (span) {\n"
    "            span.textContent = '(' + n + ')';\n"
    "            span.classList.toggle('source-count--zero', n === 0);\n"
    "          }\n"
    "        });\n"
    "        syncSourceSelectAll();\n"
    "      }\n"
    "      function apply(){\n"
    "        computeSearchScores();\n"
    "        updateSourceFacetCounts();\n"
    "        const visible = cards.filter(function(card) {\n"
    "          return cardInFilterPool(card) && sourceMatches(card);\n"
    "        });\n"
    "        const key = inputs.sortBy.value;\n"
    "        const dir = inputs.sortOrder.value === 'asc' ? 1 : -1;\n"
    "        visible.sort((a,b) => {\n"
    "          const av = key==='title' ? (a.dataset.title || '') : (key==='date' ? (parseDate(a.dataset.date || '') || 0) : num(a.dataset[key] || 0));\n"
    "          const bv = key==='title' ? (b.dataset.title || '') : (key==='date' ? (parseDate(b.dataset.date || '') || 0) : num(b.dataset[key] || 0));\n"
    "          let cmp;\n"
    "          if (typeof av === 'string' || typeof bv === 'string') {\n"
    "            cmp = String(av).localeCompare(String(bv)) * dir;\n"
    "          } else {\n"
    "            cmp = (av - bv) * dir;\n"
    "          }\n"
    "          if (cmp !== 0) return cmp;\n"
    "          if (committedQuery) {\n"
    "            const ia = parseInt(a.dataset.cardIdx, 10), ib = parseInt(b.dataset.cardIdx, 10);\n"
    "            const sa = Number.isFinite(ia) ? (searchScores[ia] || 0) : 0;\n"
    "            const sb = Number.isFinite(ib) ? (searchScores[ib] || 0) : 0;\n"
    "            if (sb !== sa) return sb - sa;\n"
    "          }\n"
    "          return 0;\n"
    "        });\n"
    "        cards.forEach(c => { c.style.display='none'; });\n"
    "        visible.forEach(c => { c.style.display='block'; container.appendChild(c); });\n"
    "        inputs.count.textContent = `${visible.length} item(s)`;\n"
    "      }\n"
    "      [inputs.dateFrom,inputs.dateTo,inputs.minRel,inputs.minImp,inputs.minNov,inputs.minTrust,inputs.minComp,inputs.sortBy,inputs.sortOrder].forEach(function(i){\n"
    "        if (i) {\n"
    "          i.addEventListener('input', apply);\n"
    "          i.addEventListener('change', apply);\n"
    "        }\n"
    "      });\n"
    "      if (inputs.searchForm) {\n"
    "        inputs.searchForm.addEventListener('submit', function(e) {\n"
    "          e.preventDefault();\n"
    "          e.stopPropagation();\n"
    "          void runSearch();\n"
    "        });\n"
    "      }\n"
    "      function syncSourceSelectAll(){\n"
    "        var master = document.getElementById('source_select_all');\n"
    "        if (!master) return;\n"
    "        var boxes = visibleSourceFilters();\n"
    "        if (!boxes.length) return;\n"
    "        var n = boxes.filter(function(b){ return b.checked; }).length;\n"
    "        master.checked = n === boxes.length;\n"
    "        master.indeterminate = n > 0 && n < boxes.length;\n"
    "      }\n"
    "      document.querySelectorAll('.source-filter').forEach(function(b){\n"
    "        b.addEventListener('change', function(){ syncSourceSelectAll(); apply(); });\n"
    "      });\n"
    "      var sourceSelectAll = document.getElementById('source_select_all');\n"
    "      if (sourceSelectAll) {\n"
    "        sourceSelectAll.addEventListener('change', function(){\n"
    "          var on = sourceSelectAll.checked;\n"
    "          visibleSourceFilters().forEach(function(b){ b.checked = on; });\n"
    "          sourceSelectAll.indeterminate = false;\n"
    "          apply();\n"
    "        });\n"
    "      }\n"
    "      var showMore = document.getElementById('source_show_more');\n"
    "      if (showMore) {\n"
    "        showMore.addEventListener('click', function(){\n"
    "          document.querySelectorAll('.source-row.source-row--extra').forEach(function(r){ r.classList.remove('source-row--extra'); });\n"
    "          showMore.style.display = 'none';\n"
    "        });\n"
    "      }\n"
    "      inputs.reset.addEventListener('click', () => {\n"
    "        inputs.dateFrom.value=''; inputs.dateTo.value=''; inputs.minRel.value='0'; inputs.minImp.value='0'; inputs.minNov.value='0'; inputs.minTrust.value='0'; inputs.minComp.value='0';\n"
    "        inputs.sortBy.value='composed'; inputs.sortOrder.value='desc';\n"
    "        if (inputs.searchQ) inputs.searchQ.value='';\n"
    "        committedQuery = '';\n"
    "        queryEmb = null;\n"
    "        var seh = document.getElementById('search_semantic_hint'); if (seh) seh.hidden = true;\n"
    "        document.querySelectorAll('.source-filter').forEach(function(b){ b.checked = true; });\n"
    "        syncSourceSelectAll();\n"
    "        apply();\n"
    "      });\n"
    "      syncSourceSelectAll();\n"
    "      apply();\n"
    "    })();\n"
)
